In [1]:
import numpy
m = numpy.arange(27)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [11]:
import cv2
image = cv2.imread("image.jfif",0)
image

array([[ 89,  97,  98, ...,  80,  80,  80],
       [ 94, 100,  98, ...,  70,  70,  70],
       [106, 112, 111, ...,  65,  65,  65],
       ...,
       [ 60,  59,  66, ...,  93,  65,  49],
       [ 52,  77,  52, ...,  95,  63,  46],
       [ 63,  63,  62, ...,  72,  62,  43]], dtype=uint8)

In [10]:
cv2.imwrite("newimage.png",image)

True

In [13]:
image[0:4,2:6]

array([[ 98,  92,  94, 102],
       [ 98,  89,  86,  91],
       [111, 101,  99, 104],
       [102,  96,  98, 106]], dtype=uint8)

In [14]:
image.shape

(177, 284)

In [15]:
for i in image.flat:
    print(i)

89
97
98
92
94
102
103
97
90
91
92
94
96
98
100
100
112
103
95
96
104
111
110
106
118
100
92
105
119
117
110
107
113
98
122
108
109
126
104
120
116
123
105
112
112
107
129
125
112
104
117
115
123
103
116
124
108
127
127
104
106
130
140
127
133
118
143
131
109
115
109
113
130
118
137
113
101
156
111
82
136
43
103
120
92
95
117
94
94
110
73
33
88
109
126
46
99
57
100
129
44
101
90
112
93
84
96
119
59
81
72
82
54
79
61
84
97
57
61
55
70
91
64
74
63
68
44
98
37
72
81
59
66
53
101
48
87
47
48
49
66
69
92
82
64
72
60
86
69
39
101
53
75
47
65
51
69
60
46
50
50
92
95
9
50
58
72
69
76
77
79
32
79
80
51
73
43
101
66
78
77
81
88
78
70
87
43
41
63
87
54
78
91
25
63
79
113
88
92
99
111
68
75
87
64
73
105
101
90
98
95
82
85
102
110
104
79
108
71
90
105
99
80
85
92
91
81
97
97
82
92
94
89
98
97
87
87
94
93
85
71
72
73
78
84
92
100
105
91
90
87
84
80
76
74
72
60
64
69
72
73
70
66
64
63
70
87
103
98
79
70
74
84
78
68
59
56
59
65
70
80
80
80
80
94
100
98
89
86
91
89
82
91
92
93
95
97
98
100
100
102
102


73
74
76
63
72
35
86
87
91
80
83
79
101
47
83
93
96
100
92
65
89
128
103
98
69
67
70
81
62
108
95
72
75
85
66
65
65
66
67
69
72
73
77
76
94
87
106
92
101
94
83
88
85
75
72
78
77
69
90
79
68
67
74
78
75
70
67
69
70
70
67
62
56
52
56
59
60
65
68
62
65
80
75
71
77
88
83
67
65
74
78
71
60
51
105
103
102
104
104
102
101
103
93
99
104
102
93
85
81
80
83
77
82
97
103
99
103
113
91
102
112
115
109
102
100
101
90
112
107
98
111
106
89
92
105
94
95
87
104
95
95
83
94
110
100
98
108
115
98
95
96
96
105
88
79
85
81
96
94
83
102
93
94
98
106
96
119
105
122
87
120
84
98
83
102
98
105
97
103
101
91
85
92
93
52
110
79
63
65
71
82
104
102
90
76
79
69
64
78
78
78
71
76
58
66
55
71
60
71
66
64
57
67
54
67
57
62
47
45
55
45
48
51
50
51
51
51
51
50
51
55
47
57
57
68
50
54
56
45
44
36
58
29
55
53
56
54
44
51
62
38
63
50
54
54
57
54
55
45
45
42
46
64
36
44
24
56
75
56
39
44
69
49
42
50
50
59
56
70
39
71
60
57
46
78
75
67
63
43
41
81
85
89
77
88
81
79
59
82
75
85
99
92
70
66
131
87
128
75
64
72
80
69
83
99
85

98
101
60
105
105
89
82
80
98
71
84
81
76
76
91
70
72
87
62
61
51
55
50
55
56
39
31
48
68
46
48
45
81
86
39
40
72
56
74
82
71
59
55
50
41
62
54
48
49
55
52
40
29
34
42
40
31
33
46
50
44
45
44
44
43
42
41
40
40
27
45
47
53
27
33
35
53
74
52
30
20
34
40
72
38
43
40
46
58
60
53
51
56
51
59
84
55
69
59
44
58
42
49
60
57
59
83
83
46
63
50
61
115
44
68
88
83
64
82
85
88
51
87
56
65
72
85
86
92
107
102
95
105
41
44
58
25
45
83
107
111
113
102
81
126
78
72
69
81
72
58
81
72
96
59
64
54
83
75
79
66
79
72
84
82
85
83
69
75
68
80
75
78
73
81
66
79
86
44
83
73
63
64
57
49
55
65
58
42
46
42
62
37
55
33
59
59
75
91
64
82
70
70
79
84
54
54
54
54
69
66
77
101
117
118
117
120
109
86
81
84
84
101
115
106
88
83
94
95
81
89
108
110
119
89
96
95
83
87
89
101
97
83
64
84
81
88
69
69
72
83
88
80
74
105
89
89
92
96
78
69
82
81
72
78
70
84
68
66
86
65
63
100
65
89
152
77
89
96
128
97
108
97
138
62
118
110
55
112
98
74
84
97
58
71
85
89
59
77
47
81
71
96
70
45
31
27
55
36
50
46
46
58
59
59
55
67
39
48
52
43
64


116
83
98
69
98
106
98
102
75
74
86
113
140
132
118
82
118
121
144
100
117
62
111
73
61
54
72
73
140
51
45
41
45
45
47
48
92
99
23
75
85
70
74
60
78
62
76
38
63
21
55
61
25
54
45
53
50
46
43
41
42
44
46
30
36
42
44
41
38
36
37
39
30
34
26
40
32
36
27
38
38
37
31
36
37
36
28
37
38
39
42
44
46
48
49
55
50
55
68
67
58
65
82
71
49
56
46
66
70
57
50
38
86
72
51
69
77
67
91
75
40
70
68
81
104
102
34
113
136
82
77
86
63
134
80
98
126
101
110
202
178
93
99
84
179
162
190
206
218
144
213
175
175
132
154
92
67
118
115
109
87
106
95
93
96
107
114
99
88
71
56
50
56
68
78
74
75
92
89
68
52
51
39
55
49
43
57
58
50
57
65
68
62
52
48
42
42
36
33
48
46
40
31
48
48
69
61
58
80
59
60
52
34
65
52
64
64
64
64
82
85
93
105
111
106
91
77
93
93
93
90
84
76
68
64
89
89
85
75
68
70
82
94
64
64
87
70
96
80
94
80
65
75
83
60
63
74
82
58
68
63
82
76
67
79
78
82
68
88
86
105
83
56
64
70
64
87
68
73
72
105
124
91
93
114
74
112
57
78
112
104
121
68
58
115
136
126
141
147
142
176
112
81
111
131
148
103
52
113
82
77
99

43
43
81
74
68
70
78
84
84
81
84
88
82
66
58
62
61
55
74
55
63
52
47
71
73
65
71
70
67
79
77
82
60
52
68
50
59
75
66
61
70
73
57
63
82
86
62
60
52
79
69
78
75
59
73
60
70
79
79
86
115
109
109
113
99
93
91
120
95
103
114
164
173
207
176
167
214
204
219
223
99
68
111
197
134
104
47
150
70
100
162
100
158
89
43
68
94
113
126
170
90
66
81
65
103
72
109
46
100
54
121
77
73
75
86
74
71
44
93
35
84
41
59
71
68
49
61
50
58
78
52
43
36
36
38
36
33
31
30
28
26
26
29
33
39
42
35
37
40
42
43
41
39
37
20
48
29
26
38
47
27
44
55
54
52
66
62
66
65
77
64
55
80
66
62
50
49
71
68
51
64
57
69
64
56
64
35
71
99
71
55
104
92
56
74
114
100
84
93
49
86
53
85
59
119
117
112
64
110
110
133
128
132
136
132
185
124
159
187
190
183
201
217
223
203
158
176
164
111
162
121
135
129
111
120
85
88
92
111
75
61
98
60
65
72
75
73
65
55
48
64
77
58
58
25
40
59
56
33
43
45
36
36
47
49
43
35
40
44
40
32
28
30
34
34
34
35
37
38
40
41
41
43
43
43
43
67
65
63
66
74
85
93
98
80
72
67
67
60
52
58
72
64
51
68
53
58
86
66
57
72
7

63
58
61
73
71
76
54
72
70
68
91
50
76
74
73
78
86
95
102
111
119
141
114
112
97
161
130
215
198
179
176
199
181
161
141
172
102
113
135
117
100
103
108
73
74
109
140
58
136
80
78
58
113
52
56
71
79
85
78
96
61
95
72
70
98
82
90
63
90
58
108
36
81
48
44
54
72
42
82
53
43
32
61
59
41
58
57
49
49
42
60
78
54
79
48
82
72
85
41
96
63
59
94
73
51
106
98
45
58
84
81
50
33
85
68
109
69
93
73
66
67
63
55
65
69
62
55
53
47
40
24
34
49
62
62
55
57
63
60
52
43
61
63
60
77
69
97
63
57
75
28
94
51
91
103
60
64
72
86
89
79
95
95
113
91
62
118
104
98
98
80
110
114
140
79
111
126
128
174
141
78
78
107
168
141
100
133
164
153
152
149
153
159
209
130
146
166
171
125
125
110
121
133
123
119
81
67
93
80
50
63
40
58
37
27
40
34
37
18
37
39
22
18
34
36
22
20
32
27
36
27
55
43
24
27
27
28
29
30
31
31
32
37
37
37
38
52
59
59
55
60
73
73
63
76
61
48
52
67
75
68
57
53
41
61
59
56
57
49
74
67
43
58
34
38
61
54
77
39
73
72
51
82
69
53
54
66
62
82
66
63
61
81
63
96
55
65
90
75
73
98
94
123
124
138
128
120
95
74
11

99
126
154
154
166
174
205
168
113
183
141
127
139
144
78
98
101
97
112
134
73
59
62
53
64
98
54
87
76
79
72
76
43
78
43
73
84
88
88
49
116
23
43
80
49
59
92
98
83
19
62
76
101
72
38
14
57
70
58
42
51
51
42
42
40
40
42
43
44
44
45
45
44
43
44
47
52
53
51
48
55
54
53
52
50
49
47
47
50
44
42
47
57
63
60
55
56
55
53
51
49
46
45
44
51
45
40
13
23
21
28
13
22
26
31
36
41
46
51
55
43
48
42
52
63
49
80
33
56
37
58
48
92
51
56
98
50
41
72
92
60
35
46
63
55
71
63
76
116
110
58
51
91
48
67
84
82
82
70
82
95
110
91
92
85
90
72
85
116
86
74
111
123
155
100
94
100
129
135
114
155
118
139
151
170
147
128
162
169
131
127
127
142
129
93
104
118
103
32
0
33
40
39
29
25
28
25
17
32
32
31
29
28
27
26
25
28
29
29
30
31
32
33
33
27
27
27
27
51
51
51
50
50
49
49
49
53
48
45
49
57
63
62
58
69
56
49
53
54
48
48
55
54
54
54
55
58
59
55
50
88
55
84
78
53
60
64
59
56
44
34
39
55
69
71
68
67
102
125
140
144
128
108
113
110
154
133
159
106
168
142
136
163
136
132
119
64
146
175
98
77
96
121
122
84
97
84
61
73
67
7

168
127
138
137
167
133
167
163
174
123
129
111
122
149
139
90
70
38
7
24
22
25
24
18
29
6
21
21
24
28
27
25
23
20
17
15
14
28
28
28
28
52
50
47
43
42
45
50
54
46
48
52
54
52
46
40
35
51
57
57
54
57
62
54
39
59
79
68
74
62
64
57
87
80
45
57
72
63
41
72
98
108
109
113
112
110
115
112
95
115
192
119
131
224
185
155
139
180
135
88
85
110
128
109
83
103
88
84
53
55
50
78
95
62
66
72
62
82
67
60
62
47
55
45
69
47
59
48
53
81
105
37
59
91
72
88
75
53
62
79
79
59
46
82
78
61
75
82
59
69
59
61
38
31
49
54
37
22
23
27
25
20
24
28
28
38
50
42
30
29
40
49
43
30
22
28
38
28
29
32
35
38
41
44
45
46
46
45
44
43
42
42
41
40
37
33
29
27
28
29
30
47
39
38
34
33
37
38
39
32
32
31
31
31
31
31
31
24
25
25
25
29
38
45
48
68
35
58
49
40
63
65
37
72
65
60
52
84
62
57
65
67
62
50
40
70
61
65
69
74
53
71
78
54
95
84
67
66
69
63
71
62
79
75
74
95
67
70
91
87
72
67
63
95
75
108
60
97
97
106
88
101
96
146
119
138
95
141
91
134
149
179
172
151
138
105
102
97
128
136
137
114
80
63
36
10
8
5
19
18
32
29
29
21
21
22


26
25
25
25
28
26
22
21
46
31
48
43
16
50
69
54
54
46
38
47
44
42
54
51
65
42
40
69
40
45
56
67
67
51
59
63
65
60
42
43
74
75
36
78
59
51
69
54
69
81
94
86
66
77
94
111
111
84
82
68
102
80
117
113
112
73
63
70
75
86
101
92
158
138
131
123
127
140
167
184
175
178
88
105
112
76
152
63
81
88
62
65
57
51
45
31
15
15
25
34
34
33
33
67
58
45
35
33
39
49
57
71
44
55
60
63
51
62
52
52
55
69
60
64
50
60
61
96
80
96
100
117
118
131
113
85
84
120
161
185
119
123
185
111
107
161
96
107
121
107
80
60
61
70
63
47
79
59
65
50
58
64
67
70
73
70
65
66
73
48
44
68
74
65
55
37
58
69
55
42
42
46
45
57
59
53
50
47
58
85
67
47
33
56
48
78
47
61
55
38
74
70
55
76
82
60
52
46
60
51
39
46
30
5
14
24
25
26
27
29
30
32
32
24
27
32
37
41
42
41
41
42
43
43
44
46
47
47
48
47
47
47
47
48
48
48
48
48
48
48
49
49
49
50
50
60
60
60
60
60
61
61
61
63
58
50
43
40
40
43
45
56
55
52
48
44
40
37
36
29
28
28
27
26
25
24
24
27
29
30
19
13
46
33
42
33
18
59
63
39
47
38
20
68
39
25
31
41
75
42
41
61
35
43
54
67
74
59
61
65
47
4

81
66
62
71
79
73
62
65
71
75
74
69
69
75
82
100
80
83
61
68
107
123
157
136
121
82
78
141
134
112
126
89
96
106
114
70
108
116
81
105
150
124
88
122
113
106
134
122
85
79
81
52
88
111
87
103
156
116
129
103
125
115
108
117
125
95
71
110
90
66
82
55
66
57
65
70
75
76
70
60
56
62
70
81
76
71
72
76
78
76
72
58
63
64
57
45
37
39
44
31
35
46
56
52
42
46
59
62
52
43
44
52
55
49
41
54
43
63
45
76
48
56
35
42
34
47
33
56
41
53
44
50
53
52
51
74
38
42
31
53
55
55
49
41
37
42
49
53
66
64
45
37
47
53
49
66
45
44
38
34
46
71
68
57
67
53
57
62
72
67
82
96
79
82
109
126
125
130
144
127
120
135
121
117
128
121
138
137
133
129
121
107
88
73
66
110
90
75
77
82
78
70
66
70
93
90
76
64
43
39
54
59
56
44
34
40
56
64
59
48
23
11
68
36
43
67
74
63
53
66
44
69
53
69
56
61
56
51
51
56
47
44
37
52
45
52
57
47
49
53
43
63
74
62
46
52
55
51
54
49
51
53
55
55
53
50
48
54
51
51
55
58
58
58
59
64
64
76
68
83
68
72
67
66
67
72
82
89
88
84
82
66
71
75
76
74
73
76
78
86
74
91
81
89
111
97
107
130
144
101
87
111
115
8

36
41
47
50
50
43
48
57
66
70
68
60
54
42
49
58
62
63
64
67
71
47
50
51
48
42
38
40
43
52
62
43
41
64
45
29
62
60
50
68
117
100
126
126
121
122
122
135
114
95
138
152
129
144
144
125
112
124
184
158
129
154
168
149
157
161
160
135
91
76
70
43
60
58
68
60
57
78
66
78
63
75
65
72
63
64
74
69
79
79
74
65
58
55
57
61
65
54
52
50
49
50
51
50
49
51
50
48
45
43
45
48
51
51
49
39
37
45
43
34
31
49
52
57
61
62
61
58
57
33
59
59
48
40
44
49
33
26
54
43
31
42
48
45
63
41
47
37
41
47
62
61
49
33
54
22
61
70
21
41
48
50
102
128
101
76
89
107
109
106
110
113
110
106
104
108
113
93
95
96
91
81
72
66
64
71
69
58
40
25
20
22
25
24
23
31
50
65
61
43
28
15
18
23
30
40
50
58
62
64
73
85
92
95
95
96
97
106
107
107
108
109
110
111
111
132
117
120
106
128
113
115
99
116
82
57
68
45
61
67
70
49
90
25
64
44
31
30
25
59
34
38
53
54
43
18
54
36
18
27
51
47
49
34
63
55
38
26
52
53
34
43
41
42
46
48
43
39
38
40
40
58
49
39
36
40
46
49
49
30
40
50
51
45
40
42
47
39
48
58
61
58
57
60
64
48
53
56
53
46
43
46
52
47
56

31
31
40
34
25
18
17
22
30
35
25
25
25
26
26
27
27
27
29
29
29
30
30
31
31
31
30
29
26
24
24
26
29
32
34
35
36
37
39
40
41
42
35
35
36
37
38
39
39
40
46
43
39
37
37
41
45
48
30
24
21
26
36
41
38
32
30
29
52
45
47
93
123
133
155
127
114
135
139
121
157
128
162
158
187
165
172
130
83
97
144
191
155
94
83
73
58
58
47
30
0
10
6
23
15
36
29
37
51
55
36
34
31
26
21
17
14
12
33
17
11
25
41
45
43
44
28
33
35
32
24
18
17
19
20
21
22
22
20
16
11
8
25
23
20
19
21
26
32
37
22
23
25
27
30
33
35
36
29
27
25
25
28
34
39
43
36
47
42
33
37
44
41
39
44
35
43
38
40
45
31
33
50
55
63
72
81
87
91
93
87
81
85
103
118
117
106
97
118
115
114
116
118
115
106
99
130
124
108
108
119
116
120
146
137
121
118
129
128
112
109
119
112
109
101
108
109
116
108
104
111
113
111
119
117
125
124
128
135
134
133
132
130
129
128
128
129
116
124
110
117
108
123
116
114
113
111
109
106
104
102
101
94
85
75
73
76
76
70
63
45
41
35
30
26
25
25
26
26
26
26
26
26
26
26
26
32
30
27
24
23
24
26
27
24
24
24
25
25
26
26
26
26
27
28
30

70
85
95
83
81
79
78
79
83
86
89
106
65
18
13
19
44
46
44
63
47
26
30
37
13
61
36
75
78
75
110
136
167
132
129
48
31
33
46
45
46
36
20
13
18
19
13
40
152
135
135
150
146
116
170
192
138
110
102
111
129
151
142
126
95
82
97
101
81
68
73
64
53
33
36
16
11
2
12
5
7
26
55
67
60
57
65
69
74
80
84
85
84
83
83
65
68
89
94
79
85
88
65
29
10
16
21
53
50
65
65
59
64
67
67
67
66
62
57
61
51
24
12
23
19
4
3
11
9
24
19
40
35
49
46
46
48
50
53
54
52
47
43
67
65
69
77
80
75
66
61
98
77
60
77
68
62
59
80
75
63
77
68
92
91
94
89
79
80
81
82
84
85
86
87
96
95
95
94
93
92
91
91
100
94
89
89
91
91
86
81
79
78
80
85
90
88
79
71
74
62
75
63
68
57
70
58
56
60
64
67
64
57
49
44
51
47
46
52
58
50
28
9
18
11
14
29
37
34
34
40
67
68
73
78
81
82
73
59
39
40
32
28
28
17
10
19
29
60
89
96
92
89
85
79
85
84
93
94
90
98
97
74
85
77
66
55
44
29
12
1
4
37
50
57
65
76
88
73
59
58
58
59
64
71
79
83
90
88
86
87
92
100
109
115
129
130
95
56
9
36
44
39
50
32
2
12
17
20
67
78
99
85
82
116
151
135
95
85
66
63
56
55
31
36
32
2

90
120
90
99
103
101
100
98
84
66
66
27
15
10
10
8
6
33
47
82
101
94
87
86
88
93
85
88
114
117
129
108
117
120
100
95
91
91
93
89
79
70
37
27
32
46
50
56
69
78
64
71
75
78
92
110
113
105
100
108
100
81
77
75
62
48
27
32
38
42
42
37
30
25
12
26
42
49
46
41
38
38
39
39
40
41
44
48
52
54
55
53
51
49
51
55
59
62
58
58
59
59
60
60
60
61
62
62
61
61
61
60
60
60
57
58
58
59
60
61
62
62
59
60
60
60
61
61
62
62
55
54
53
52
50
49
48
47
48
45
42
38
37
37
39
41
35
34
34
33
32
31
30
30
17
19
18
12
9
18
37
53
55
48
73
141
160
104
73
112
106
108
114
116
104
79
55
44
57
53
39
32
26
15
38
86
68
65
106
114
114
115
107
97
118
126
111
116
123
119
113
81
89
93
86
90
59
37
4
0
8
23
48
63
63
69
73
86
81
89
91
88
76
72
68
67
61
69
75
76
73
60
60
53
65
129
154
155
143
131
133
32
37
61
64
64
40
69
80
85
46
72
75
63
106
106
134
102
82
141
89
68
67
63
36
68
64
101
80
81
173
133
118
138
123
87
95
89
89
87
106
97
101
108
124
103
106
107
106
105
112
112
91
64
66
25
12
9
10
8
7
36
46
89
106
97
97
97
97
108
102
111
10

58
94
111
101
122
119
128
107
92
101
109
136
109
123
145
130
127
122
134
63
37
8
6
20
19
28
52
66
37
85
97
98
104
115
128
113
97
99
90
92
91
87
95
92
88
83
93
82
41
28
42
42
39
33
60
79
81
81
106
115
90
97
108
116
136
142
130
106
108
93
79
70
64
57
56
58
86
79
61
54
62
69
73
80
78
61
37
25
33
49
53
48
36
50
53
48
55
66
56
32
44
47
48
44
40
43
52
61
47
47
49
53
57
56
51
46
52
57
57
48
54
60
60
48
53
62
58
70
67
54
64
63
51
54
58
61
61
59
55
53
50
40
47
40
41
48
35
39
39
37
35
34
35
38
43
46
35
34
32
32
34
37
41
44
31
27
32
47
54
55
60
70
63
58
52
49
51
58
66
72
57
54
50
46
43
42
42
42
27
26
24
22
19
17
15
14
45
53
40
33
57
78
79
79
52
50
47
47
51
59
68
73
53
57
66
77
83
77
63
51
22
2
4
3
9
21
23
45
62
58
52
48
47
51
56
60
56
53
49
46
46
48
52
54
59
62
49
64
82
82
110
149
151
149
128
76
85
81
41
62
40
50
73
63
118
103
85
100
100
66
44
59
79
72
44
69
70
130
145
166
141
184
143
113
77
93
115
119
138
129
128
115
112
122
125
138
107
117
134
132
118
120
121
63
51
16
9
29
36
37
50
62
89
143
12

35
37
25
25
16
30
23
16
16
20
23
22
20
19
20
21
22
23
25
26
26
18
19
19
20
21
22
22
23
27
26
24
22
20
17
16
15
16
23
21
12
16
33
42
39
38
38
39
41
42
44
45
45
39
33
30
35
45
50
46
40
40
43
39
26
9
1
6
14
21
37
44
35
27
33
42
45
43
43
44
44
45
45
46
46
44
52
42
47
48
49
73
77
71
68
101
123
112
55
51
73
63
66
71
76
91
87
57
90
110
86
93
89
92
98
97
74
135
132
139
137
107
111
91
118
96
107
92
121
101
114
113
129
115
126
117
124
121
118
122
115
96
96
103
94
99
95
115
119
119
125
118
117
106
103
116
115
129
112
103
85
85
97
109
110
91
69
73
95
57
51
44
68
84
82
88
84
88
84
79
73
69
66
65
65
75
63
52
52
59
61
54
44
34
38
42
42
39
37
37
38
48
48
51
58
63
58
45
34
27
26
21
13
6
8
19
28
45
47
34
48
40
57
51
57
51
54
57
55
53
52
54
57
68
56
45
48
61
71
71
66
75
87
86
87
76
63
72
73
85
76
60
50
77
57
71
57
47
45
70
68
55
49
66
73
39
54
49
68
66
80
59
58
56
62
39
47
46
58
40
51
40
29
43
32
36
22
33
19
26
20
14
14
19
24
23
21
18
19
21
23
26
28
29
30
32
33
34
36
37
39
40
41
23
22
21
20
19
18
17
16
1

36
24
25
22
31
25
38
34
45
44
36
36
36
41
14
23
29
33
20
32
37
30
28
35
40
38
17
17
18
17
17
17
17
18
17
27
18
12
19
11
0
8
4
4
4
5
5
6
6
6
10
11
11
12
13
14
15
15
11
11
11
11
11
11
11
11
9
10
11
12
14
15
16
17
25
25
25
25
25
25
25
25
24
24
25
26
27
28
28
29
41
42
60
44
29
31
24
42
38
30
35
36
24
29
40
36
49
48
45
42
39
35
33
31
40
40
26
33
22
40
39
49
41
34
15
44
63
29
40
68
61
95
63
46
63
63
62
46
38
62
78
62
53
92
61
56
69
55
68
70
63
82
98
81
91
97
108
95
93
95
106
77
102
101
112
87
100
79
100
132
96
103
107
87
82
84
106
82
85
85
82
80
86
89
56
50
57
49
53
54
52
56
61
64
63
58
52
47
46
40
46
40
53
43
43
33
41
46
33
39
39
35
48
43
46
40
32
26
27
33
42
48
33
30
18
5
5
14
13
4
6
6
6
6
6
6
6
6
3
3
4
5
6
7
8
8
8
9
10
12
14
16
17
18
34
38
29
17
28
48
45
25
34
42
35
31
40
36
29
37
28
35
26
30
26
45
35
28
32
35
28
36
25
33
26
29
26
31
35
34
30
29
33
38
45
26
21
35
38
24
19
28
22
25
28
31
32
31
29
27
24
19
15
15
18
19
14
10
11
19
21
15
13
17
13
4
4
4
5
5
6
6
7
7
6
6
7
9
10
11
12
13
15
15
15

In [16]:
# Stacking and splitting numpy arrays

In [17]:
img = numpy.hstack((image,image))

In [18]:
img

array([[ 89,  97,  98, ...,  80,  80,  80],
       [ 94, 100,  98, ...,  70,  70,  70],
       [106, 112, 111, ...,  65,  65,  65],
       ...,
       [ 60,  59,  66, ...,  93,  65,  49],
       [ 52,  77,  52, ...,  95,  63,  46],
       [ 63,  63,  62, ...,  72,  62,  43]], dtype=uint8)

In [19]:
img.shape

(177, 568)